spring:
  application:
    name: audit-trails
  datasource:
    url: jdbc:postgresql://localhost:5432/audit_trails
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
    #        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect