spring:
  application:
    name: audit-trails
  datasource:
    url: jdbc:postgresql://localhost:5432/audit_trails
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        #format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate:
        stat: DEBUG
        sql: DEBUG

application:
  security:
    jwt:
      secret-key: 67566B59703373367639792F423F4528482B4D6251655468576D5A7134743777
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days